### ISSUE TITLE
Email password resets

### ISSUE THREAD

**Issue by alanmoo** [coralproject/shelf-auth#13]
(I think this is the right repo for this, I'll move it if not though)

As we use Ask at MoFo, we're setting up accounts for users and need to get their passwords to them, which is sometimes frustrating to coordinate in a secure manner. Is a password reset email something that's planned for this or even something that might be an option for a contributor to work on? If the latter, could someone familiar with what might need to be done lay out some rough guidance in case someone comes across this and wants to work on it? (We occasionally have contributors who want to work on things and I'd love to be able to direct them to this.)

cc @losowsky

**Comment by jtnelson** [comment]
@alanmoo We're scoping out a re-write of Ask and one of the things we want to tackle is better user management

@wyattjoh can provide more details. We'd love some contributor help on the re-write.

**Comment by wyattjoh** [comment]
As @jtnelson, we are in progress of a ground up rewrite of Ask that should make such tasks muchhhhhh easier. We'll update with more details as we can, but to assure you, we already have password reset implemented in the rewrite :)

**Comment by alanmoo** [comment]
Great, sounds like you don’t need this issue then. Thanks for the info!
